@startuml

interface Lector{
    +obtener():ArrayList
    +esDeTipo():boolean
}

abstract class LectorDePaises{
}

abstract class LectorDeCartas{
}

class LectorDeCartasJSON {
}

class LectorDePaisesJSON {
}

class LectorDeObjetivos {
}

class LectorDeObjetivosJSON{
}

FachadaLector ..> Lector
Lector <|.right.LectorDePaisesJSON
Lector <|.left. LectorDeCartasJSON
Lector <|.. LectorDeObjetivosJSON
LectorDeCartas <|-- LectorDeCartasJSON
LectorDePaises <|-- LectorDePaisesJSON
LectorDeObjetivos <|-- LectorDeObjetivosJSON

@enduml