@startuml

class FachadaLector{

}
interface Lector{
    +{abstract}obtener():ArrayList
    +{abstract}esDeTipo():boolean
}
class LectorDeCartasJSON {

}
class LectorDePaisesJSON {
    -obtenerPais():Pais
}
class LectorDeCartasCSV {

}

class LectorDePaisesCSV {

}

abstract class LectorDePaises{
    +inicializarContinentes():ArrayList
    +{abstract}organizarContinentes():void
}

abstract class LectorDeCartas{
    +{abstract}obtenerCarta:Carta
}

FachadaLector ..> Lector
Lector <|.. LectorDePaises
Lector <|.. LectorDeCartas
LectorDeCartas <|-- LectorDeCartasJSON
LectorDeCartas <|-- LectorDeCartasCSV
LectorDePaises <|-- LectorDePaisesJSON
LectorDePaises <|-- LectorDePaisesCSV

@enduml