@startuml diagrama
Actor Usuario
Usuario++

Usuario -> Juego: atacarPais()

note right
Aqui iria una comprobacion
de si el pais atacado y atacante 
le corresponde a cada jugador
(consulta al corrector si corresponde)
end note

Juego++

loop cantidadTotalEjercitos
    Juego -> Juego: lanzarDados():Integer
end

loop cantidadTotalEnfrentamientos

    Juego -> Juego: determinarPerdedor():Pais

    Juego -> Jugador: atacarPais():void

    Jugador++

    Jugador -> paisAtacante: serAtacado():void

    paisAtacante++
    paisAtacante--
    
    Jugador -> paisAtacado: serAtacado():void

    paisAtacado++
    paisAtacado--
    Jugador--
end

Juego -> Jugador: moverEjercito():void
Jugador++
Jugador--

Juego -> Jugador: objetivoCumplido():void
Jugador++

Jugador -> Objetivo: cumplido():void
Jugador--

Objetivo++
Objetivo--

Juego--

@enduml