@startuml diagrama
Actor Usuario
Usuario++
Usuario -> Juego: atacarPais()
Juego++
Juego -> Batalla**: <create>
Batalla --> Juego: Batalla
Juego -> Batalla: lanzarDados()
Batalla++
Juego -> Batalla: batallar()
Batalla -> Batalla: ataqueEntrePaises
loop cantidad minima de dados
    Batalla -> Batalla: determinarPerdedor()
    Participant "perdedor: Pais" as perdedor
    Batalla -> perdedor: serAtacado()
    perdedor++
end
    Batalla -> Batalla: conquista()
    Participant "paisAtacado: Pais" as paisAtacado
    Batalla -> paisAtacado: serConquistadoPor()
    paisAtacado++
    Participant "paisAtacante: Pais" as paisAtacante
    Batalla -> paisAtacante: moverEjercito()
    paisAtacante++
@enduml