@startuml
Batalla ++
Participant "paisAtacado: Pais" as paisAtacado
Participant "duenio: Jugador" as duenio
Participant "conquistador: Jugador" as conquistador
Participant "paisAtacante: Pais" as paisAtacante
Batalla -> paisAtacado: serConquistadoPor()
paisAtacado++
paisAtacado -> duenio: perderPais()
duenio++
paisAtacado -> conquistador: agregarPais()
conquistador++
conquistador -> paisAtacado: asignarDuenio()
Batalla -> paisAtacante: moverEjercitos()
paisAtacante++
paisAtacante -> paisAtacado: agregarEjercitos()

@enduml